-- MySQL Script generated by MySQL Workbench
-- Fri Apr 30 13:44:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_Personas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_Personas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_Personas` DEFAULT CHARACTER SET utf8 ;
USE `DB_Personas` ;

-- -----------------------------------------------------
-- Table `DB_Personas`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_Personas`.`PERSONA` (
  `ID_PERSONA` INT NOT NULL,
  `NOMBRES` VARCHAR(50) NOT NULL,
  `APELLIDOS` VARCHAR(50) NOT NULL,
  `SEXO` VARCHAR(50) NOT NULL,
  `FECHA_NACIMIENTO` DATE NOT NULL,
  `SALARIO` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`ID_PERSONA`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `db_personas`.`persona`(`ID_PERSONA`,`NOMBRES`,`APELLIDOS`,`SEXO`,
`FECHA_NACIMIENTO`,`SALARIO`)
VALUES(1052415672,"Juan Manuel","Cardona Perez","Masculino",
"1995-05-22",125000.00);

INSERT INTO `db_personas`.`persona`(`ID_PERSONA`,`NOMBRES`,`APELLIDOS`,`SEXO`,
`FECHA_NACIMIENTO`,`SALARIO`)
VALUES(10557483,"Laura Carolina","Rodriguez Mesa","Femenino",
"1992-10-22",890000.00);

INSERT INTO `db_personas`.`persona`(`ID_PERSONA`,`NOMBRES`,`APELLIDOS`,`SEXO`,
`FECHA_NACIMIENTO`,`SALARIO`)
VALUES(19256783,"Daniel Camilo","Orjuela Sisa","Masculino",
"1982-03-08",990000.00);

INSERT INTO `db_personas`.`persona`(`ID_PERSONA`,`NOMBRES`,`APELLIDOS`,`SEXO`,
`FECHA_NACIMIENTO`,`SALARIO`)
VALUES(678902356,"Santiago Daniel","Sanchez Lopez","Masculino",
"2012-06-28",678000.00);

INSERT INTO `db_personas`.`persona`(`ID_PERSONA`,`NOMBRES`,`APELLIDOS`,`SEXO`,
`FECHA_NACIMIENTO`,`SALARIO`)
VALUES(25671821,"Carmen Fabiola","Peña Uribe","Femenino",
"1990-08-30",900250.00);

INSERT INTO `db_personas`.`persona`(`ID_PERSONA`,`NOMBRES`,`APELLIDOS`,`SEXO`,
`FECHA_NACIMIENTO`,`SALARIO`)
VALUES(1234642765,"Carlos Arturo","Saldarriaga Navas","Masculino",
"1989-12-08",888900.00);

INSERT INTO `db_personas`.`persona`(`ID_PERSONA`,`NOMBRES`,`APELLIDOS`,`SEXO`,
`FECHA_NACIMIENTO`,`SALARIO`)
VALUES(987152712,"Karen Daniela","Muñoz Mesa","Femenino",
"2011-12-02",970400.00);

INSERT INTO `db_personas`.`persona`(`ID_PERSONA`,`NOMBRES`,`APELLIDOS`,`SEXO`,
`FECHA_NACIMIENTO`,`SALARIO`)
VALUES(450780.20,"Mauricio Ricardo","Chacon Valcarcel","Masculino",
"1991-09-12",875600.00);

INSERT INTO `db_personas`.`persona`(`ID_PERSONA`,`NOMBRES`,`APELLIDOS`,`SEXO`,
`FECHA_NACIMIENTO`,`SALARIO`)
VALUES(1053426712,"Karol Pilar","Socha Marquez","Femenino",
"1993-06-27",998300.00);

INSERT INTO `db_personas`.`persona`(`ID_PERSONA`,`NOMBRES`,`APELLIDOS`,`SEXO`,
`FECHA_NACIMIENTO`,`SALARIO`)
VALUES(106789203,"Camilo Andres","Triana Rodriguez","Masculino",
"2014-02-12",789000.00);

